export const GET_TODOS = 'GET_TODOS';
export const GET_TODOS_PROGRESS = 'GET_TODOS_PROGRESS';
export const GET_TODOS_FAILED = 'GET_TODOS_FAILED';

export const ADD_TODO = 'ADD_TODO';
export const ADD_TODO_PROGRESS = 'ADD_TODO_PROGRESS';
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED';

export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_TODO_PROGRESS = 'DELETE_TODO_PROGRESS';
export const DELETE_TODO_FAILED = 'DELETE_TODO_FAILED';

export const SELECT_TODO = 'SELECT_TODO';
export const SELECT_TODO_PROGRESS = 'SELECT_TODO_PROGRESS';
export const SELECT_TODO_FAILED = 'SELECT_TODO_FAILED';
